CREATE DATABASE AFRDVS;

USE AFRDVS;

CREATE TABLE Admin (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  ref VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Client (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  age INT NOT NULL,
  prefession VARCHAR(50) NOT NULL,
  ref VARCHAR(255) NOT NULL UNIQUE,
  idAdmin INT,
  CONSTRAINT fk_admin FOREIGN KEY (idAdmin) REFERENCES Admin(id)
);


CREATE TABLE RDVs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sujet_rdv VARCHAR(255) NOT NULL,
  date_rdv DATE NOT NULL,
  creneau_rdv INT NOT NULL CHECK(creneau_rdv > 0 && creneau_rdv <= 5),
  idClient INT ,
  idAdmin INT , 
  CONSTRAINT fk_rdv_client FOREIGN KEY (idClient) REFERENCES Client(id),
  CONSTRAINT fk_rdv_admin FOREIGN KEY (idAdmin) REFERENCES Admin(id)
);
